#ifndef CHATDATABASEPROJECT_DEFINES_H
#define CHATDATABASEPROJECT_DEFINES_H

#define CHAT_IMAGE_SIZE 50
#define USER_MESSAGE_IMAGE_SIZE 40
#define AVATAR_IN_CHAT_IMAGE_SIZE 30
#define CHAT_DIALOG_AVATAR_IMAGE_SIZE 100

#define APP_PAGE 1

#define AUTHENTICATION_PAGE 0

#define AUTHORIZATION_PAGE 0

#define REGISTRATION_PAGE 1

#define CHAT_LIST_PAGE 0

#define MESSAGES_PAGE 1

#define CHOOSE_FILE_PAGE_WIDTH 705
#define CHOOSE_FILE_PAGE_HEIGHT 325

#define EDITOR_PAGE_WIDTH 900
#define EDITOR_PAGE_HEIGHT 700

#define MESSAGE_LINE_WIDTH 435

enum ROLE {
    ADMIN,
    PARTICIPANT,
    VIEWER
};

enum MESSAGE_TYPE {
    USER_MESSAGE,
    SYSTEM_MESSAGE
};

#endif //CHATDATABASEPROJECT_DEFINES_H
